const FEED_URL="https://script.google.com/macros/s/AKfycbydWsFlSeIE2kExls6H4miVySGRCE7JQn7MEWlOn97l_ciQQAKEqsAts5XiVbFottDD/exec";
const FORM_URL="https://forms.gle/Tc67D7DiD8yyUrN97";
const CALENDAR_URL="https://calendar.google.com/calendar/u/0?cid=OTJhYjFkZDIzYzJmYWNhODYyMGQ3MzE1MmQ2Njk1MDZkNDY4MTI3MzRiZWQzZGQyYjY0YmM1N2JmZDljYjdhZUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t";
let events=[];
const $=id=>document.getElementById(id);
$('form-link').href=FORM_URL;$('calendar-link').href=CALENDAR_URL;
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function safeUrl(value){try{const u=new URL(value);return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
function toEvent(item,index){const dateValue=Number(item.dateValue)||0,date=new Date(dateValue),valid=dateValue>0&&!Number.isNaN(date.getTime()),area=item.area||'Spokane Area',travelRequired=/conference/i.test(item.type||'')&&!/spokane region|cda/i.test(area);return{id:index+1,title:item.eventName||'Untitled event',dateValue,date:item.date||'Date coming soon',day:valid?new Intl.DateTimeFormat('en-US',{day:'2-digit',timeZone:'America/Los_Angeles'}).format(date):'—',month:valid?new Intl.DateTimeFormat('en-US',{month:'short',timeZone:'America/Los_Angeles'}).format(date).toUpperCase():'TBD',year:valid?new Intl.DateTimeFormat('en-US',{year:'numeric',timeZone:'America/Los_Angeles'}).format(date):'',time:item.time||'Time coming soon',location:item.location||'Location coming soon',type:travelRequired?'Out-of-Area Conference':item.type||'Event',area,description:item.description||'Open the flyer for complete event details.',featured:Boolean(item.featured),bring:item.bring||'',children:item.children||'',flyerLink:safeUrl(item.flyerLink),calendarUrl:safeUrl(item.calendarUrl),travelRequired,sourceArea:item.sourceArea||''};}
function tag(text,cls=''){return text?`<span class="${cls}">${esc(text)}</span>`:'';}
function renderNext(){const e=events[0];$('next-card').innerHTML=e?`<p>UP NEXT</p><div class="nextDate"><strong>${esc(e.day)}</strong><span>${esc(e.month)}<br>${esc(e.year)}</span></div><div><h2>${esc(e.title)}</h2><p>${esc(e.time)} · ${esc(e.area)}</p></div><a href="#event-${e.id}">See the details <span>→</span></a>`:`<p>UP NEXT</p><div><h2>More events are coming</h2><p>Check back soon for the next gathering.</p></div>`;}
function render(){const q=$('search').value.toLowerCase(),type=$('type-filter').value,area=$('area-filter').value;const filtered=events.filter(e=>(type==='All events'||e.type===type)&&(area==='All areas'||e.area===area)&&`${e.title} ${e.location} ${e.description}`.toLowerCase().includes(q));$('results-count').textContent=`${filtered.length} upcoming ${filtered.length===1?'event':'events'}`;$('clear-filters').classList.toggle('hidden',type==='All events'&&area==='All areas'&&!q);$('event-list').innerHTML=filtered.length?filtered.map(e=>`<article class="eventCard ${e.featured?'featured':''}" id="event-${e.id}"><div class="dateTile"><span>${esc(e.month)}</span><strong>${esc(e.day)}</strong></div><div class="eventMain"><div class="tags">${tag(e.sourceArea,'sourceTag')}${tag(e.type)}${e.travelRequired?tag('Travel Required','travelTag'):''}${tag(e.area)}</div><h3>${esc(e.title)}</h3><p class="meta">${esc(e.time)} <b>·</b> ${esc(e.location)}</p><div class="eventDetails hidden" id="details-${e.id}"><p>${esc(e.description)}</p>${e.children?`<p><strong>Children:</strong> ${esc(e.children)}</p>`:''}${e.bring?`<p><strong>What to bring:</strong> ${esc(e.bring)}</p>`:''}<p>⌖ ${esc(e.location)}</p>${e.flyerLink?`<p><a href="${e.flyerLink}" target="_blank" rel="noreferrer">View the event flyer ↗</a></p>`:''}</div></div><div class="cardActions"><button data-id="${e.id}">Details</button>${e.calendarUrl?`<a href="${e.calendarUrl}" target="_blank" rel="noreferrer">＋ Calendar</a>`:''}</div></article>`).join(''):`<div class="empty"><strong>No events match those filters.</strong><p>Try clearing one filter or searching another word.</p></div>`;document.querySelectorAll('.cardActions button').forEach(button=>button.addEventListener('click',()=>{const d=$(`details-${button.dataset.id}`),hidden=d.classList.toggle('hidden');button.textContent=hidden?'Details':'Less info';}));}
function addOptions(id,values,first){$(id).innerHTML=[first,...new Set(values)].map(x=>`<option>${esc(x)}</option>`).join('');}
function showFlyer(f){if(!f?.image)return;const image=safeUrl(f.image),link=safeUrl(f.flyerLink)||image;if(!image)return;$('monthly-flyer-title').textContent=`${f.month||'Monthly'} ${f.year||''} Flyer of Flyers`;$('monthly-flyer-image').src=image;$('monthly-flyer-link').href=link;$('monthly-flyer-image-link').href=link;$('monthly-flyer').classList.remove('hidden');}
function loadFeed(){const callback=`regionalEvents_${Date.now()}`,script=document.createElement('script');let finished=false;const fail=()=>{if(finished)return;finished=true;$('event-list').innerHTML='<div class="empty"><strong>The event list could not load.</strong><p>Please use the full regional calendar above while the connection is restored.</p></div>';$('results-count').textContent='0 upcoming events';};window[callback]=payload=>{finished=true;events=(payload.events||[]).map(toEvent).sort((a,b)=>a.dateValue-b.dateValue);addOptions('type-filter',events.map(e=>e.type),'All events');addOptions('area-filter',events.map(e=>e.area),'All areas');showFlyer(payload.nextMonthlyFlyer||payload.currentMonthlyFlyer);renderNext();render();delete window[callback];script.remove();};script.src=`${FEED_URL}?action=feed&callback=${callback}`;script.onerror=fail;document.body.appendChild(script);setTimeout(fail,15000);}
['search','type-filter','area-filter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('clear-filters').addEventListener('click',()=>{$('search').value='';$('type-filter').value='All events';$('area-filter').value='All areas';render();});loadFeed();
